<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sAlexandru Tone%s'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php // echo sprintf($this->translate(' %sAlexandru Tone%s '), '<a href="http://ro.linkedin.com/pub/alexandru-tone/a/406/a6b" target="_blank">', '</a>') ?></p>
    <p><a class="btn btn-success btn-lg" href="http://ro.linkedin.com/pub/alexandru-tone/a/406/a6b" target="_blank"><?php echo $this->translate('View LinkedIn profile') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Web applications') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('')) ?></p>
                <p><a class="btn btn-success pull-right" href="http://ro.linkedin.com/pub/alexandru-tone/a/406/a6b" target="_blank"><?php echo $this->translate('Web applications') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('E-commerce') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('')) ?></p>
                <p><a class="btn btn-success pull-right" href="http://ro.linkedin.com/pub/alexandru-tone/a/406/a6b" target="_blank"><?php echo $this->translate('E-commerce') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate(' &amp; Mobile sites') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('')) ?></p>
                <p><a class="btn btn-success pull-right" href="http://ro.linkedin.com/pub/alexandru-tone/a/406/a6b" target="_blank"><?php echo $this->translate('Mobile sites') ?> &raquo;</a></p>
            </div>
        </div>
    </div>
</div>
